(require 'cask "~/.cask/cask.el")
(cask-initialize)
(require 'pallet)
(add-to-list 'load-path "~/.emacs.d/custom")

(load "00common-setup.el")
(load "001mode-line.el")
(load "01ruby.el")
(load "02clojure.el")
(load "03org.el")
(load "04auto-complete.el")
(load "05web-mode.el")
(load "06highlight-indentation.el")
(load "07projectile.el")
